### ISSUE TITLE
It is not immediately visible that the content for the blog is AI generated

### ISSUE THREAD

**Issue by UweKrause** [DerekCuevas/derekcuevas.github.io#2]
Congratulation, your project gets indexed by search crawlers and people (like me) read the content.
After a more or less interesting (slightly outdated) blog post about the Elixir implementation of the actor model, I noticed that the content is AI generated.

I would expect auto generated content (especially when published as is, without further checking by a human!) to be marked as such.
Please better mark your content as auto generated.

I asked chat GPT to provide some suggestions:

Prompt:
> A blog publishes information that are created by artificial intelligence on the internet. It is not immediately visible that the blog posts are created by an AI. Please write suggestions for the author, how it might be possible to better mark auto generated content as auto generated.

Answer (read and checked by my. No changes to the text of original answer. Changes to the formatting):
> It's important to be transparent with your readers when it comes to content generated by artificial intelligence. This helps build trust and ensures that your audience is well-informed about the nature of the content they are consuming. Here are some suggestions on how to better mark auto-generated content as such:
> 1. **Clear Introductory Statement**: Begin each auto-generated blog post with a brief introductory statement that clearly indicates the content has been created by an AI. For example: "This article was generated by an artificial intelligence program."
> 2. **Author Information**: Include a byline or author box that states the content was produced by an AI algorithm. For instance: "Author: AI Writer."
> 3. **Disclaimer Banner**: Place a prominent disclaimer banner at the top of the page indicating that the content has been auto-generated. This could be a visually distinct element that's hard to miss.
> 4. **Meta Tags**: Use appropriate meta tags in the HTML of the blog posts to indicate that the content is AI-generated. This helps search engines and other platforms correctly categorize the content.
> 5. **Watermark or Symbol**: Incorporate a watermark or a small symbol in the corner of auto-generated images or graphics within the content. This subtly conveys that the content is AI-assisted.
> 6. **Consistent Terminology**: Use consistent terminology throughout your blog to refer to content that's been generated by AI. This will educate your readers and reinforce the fact that they're reading AI-assisted content.
> 7. **Dedicated Section**: Create a dedicated section on your blog's homepage or menu that explains your AI-generated content and its purpose. This way, readers can learn about it before delving into the posts.
> 8. **About Page**: Include a detailed explanation about your AI content generation process on your blog's "About" or "FAQ" page. This provides transparency to curious readers.
> 9. **Visual Cue**: Design a unique visual cue, such as a small AI icon, that appears next to the title or at the beginning of auto-generated posts. This helps readers quickly recognize AI content.
> 10. **Transparency Policy**: Draft and publish a transparency policy that outlines your commitment to disclosing AI-generated content. This demonstrates your dedication to maintaining ethical content practices.
> 11.  **Alternate Category**: If your blog has categories, consider creating a separate category specifically for AI-generated content. This assists readers in identifying which content is machine-generated.
> 12. **Regular Reminders**: Periodically, perhaps at the end of auto-generated articles, gently remind readers that they've been engaging with AI-assisted content.
> 13. **Feedback Loop**: Encourage readers to provide feedback on AI-generated content. This engagement not only helps improve your content but also reinforces the AI's involvement.
>
> Remember, the goal is to maintain openness and honesty with your readers. Implementing a combination of these strategies can help your audience better understand and appreciate the role of AI in your content creation process.

Suggestion #4 is especially funny, since as far as I know (and after a very quick internet search) I don't think that there really is a way to do this.

**Comment by DerekCuevas** [comment]
Hey, thanks for checking out the project and taking the time to provide feedback, I appreciate it! It's very fitting with the theme of the project to use ChatGPT to help brainstorm these improvements 😄.

I think many users who find themselves on the site respond like you and are surprised (and sometimes displeased) to see that the content is not human-generated, so this makes total sense. I'll try to incorporate some of these ideas when I have more time to contribute next.

**Comment by DerekCuevas** [comment]
Published this change https://github.com/DerekCuevas/derekcuevas.github.io/commit/668998d8e616fa1acdf1464d941bb82511a033ea

<img width="765" alt="Screen Shot 2023-09-03 at 7 46 25 AM" src="https://github.com/DerekCuevas/derekcuevas.github.io/assets/6598540/a665b73d-d3da-4bdb-8735-85d6cb090647">
